SELECT *
FROM TEST.USER WITH UR;


SELECT
  USER_NAME,
  SUM(CASE WHEN USER_PASSWD IS NOT NULL AND USER_PASSWD <> ''
    THEN 1
      ELSE 0 END) AS CNT
FROM
  TEST.USER
GROUP BY
  USER_NAME
ORDER BY
  CNT ASC WITH UR;



--CREATE SCHEMA TEST;
SELECT * FROM TEST.USER;


CREATE
TABLE
  TEST.USER(
  USER_ID VARCHAR(16) NOT NULL,
  USER_NAME VARCHAR(16),
  USER_PASSWD VARCHAR(16),
  CONSTRAINT PK_TEST_USER_USER_ID PRIMARY KEY (USER_ID)
);
